image:
  file: Dockerfile
checkoutLocation: "shopware"
workspaceLocation: "."
ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - name: Start apache
    command: >
        apachectl start;
