image:
  file: Dockerfile
checkoutLocation: "shopware"
workspaceLocation: "."
ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - name: Start Apache
    command: >
        apachectl start;
  - name: Start MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld &
        sleep 5;
